import roslibpy

GAS_CH4_TOPIC = '/gas/ch4_ppm'


class CH4_Topic:
    def __init__(self, client):
        # --- Setup client by parameter
        self.__ros_client = client

        # --- Setup subscriber attributes
        self.__gas_ch4_subscriber = None

        # --- Setup frame attribute
        self.__gas_value = None

        # --- Setup subscriber topic
        self.__subscribe_ch4_topic()

    # method to subscribe the ch4 data, generated by ROS
    def __subscribe_ch4_topic(self):
        self.__gas_ch4_subscriber = roslibpy.Topic(
            self.__ros_client,
            GAS_CH4_TOPIC,
            'std_msgs/Float32'
        )
        self.__gas_ch4_subscriber.subscribe(self.receive_ch4_data)

    # callback method to receive ch4 data
    def receive_ch4_data(self, message):
        self.__gas_value = int(message['data'])

    def get_ch4_value(self):
        return self.__gas_value

