import roslibpy

GAS_CO2_TOPIC = '/gas/co2_ppm'


class CO2_Topic:
    def __init__(self, client):
        #--- Setup client by parameter
        self.__ros_client = client

        #--- Setup subscriber attributes
        self.__gas_co2_subscriber = None

        #--- Setup frame attribute
        self.__gas_value = None

        #--- Setup subscriber topic
        self.__subscribe_co2_topic()

    #method to subscribe the co2 data, generated by ROS
    def __subscribe_co2_topic(self):
        self.__gas_co2_subscriber = roslibpy.Topic(
            self.__ros_client,
            GAS_CO2_TOPIC,
            'std_msgs/Float32'
        )
        self.__gas_co2_subscriber.subscribe(self.receive_co2_data)

    #callback method to receive co2 data
    def receive_co2_data(self, message):
        self.__gas_value = int(message['data'])

    def get_co2_value(self):
        return self.__gas_value

