from rclpy.node import Node
from std_msgs.msg import Float32

GAS_CO2_TOPIC = '/gas/co2_ppm'


class CO2_Topic(Node):
    def __init__(self):
        super().__init__('co2_topic_node_subscription')

        #--- Setup subscriber attributes
        self.__gas_co2_subscriber = None

        #--- Setup frame attribute
        self.__gas_value = None

        #--- Setup subscriber topic
        self.__subscribe_co2_topic()

    #method to subscribe the co2 data, generated by ROS
    def __subscribe_co2_topic(self):
        self.__gas_co2_subscriber = self.create_subscription(
            Float32,
            GAS_CO2_TOPIC,
            self.receive_co2_data, #callback
            10 #queue size
        )
        

    #callback method to receive co2 data
    def receive_co2_data(self, message):
        self.__gas_value = int(message.data)

    def get_co2_value(self):
        return self.__gas_value

